### ISSUE TITLE
Opacity?

### ISSUE THREAD

**Issue by rlaferla** [carsonperrotti/CNPGridMenu#13]
The background blur completely obscures the background.  I want to show the underlying user interface view a bit more.  I tried modifying the opacity but it's overridden or ignored by the code.  Please either suggest a way to change the alpha/opacity or add a method to do so.

**Comment by carsonperrotti** [comment]
This is something I struggled with when building this library myself. So, let me give you a quick rundown here. 

UIVisualEffectView does not offer a way to adjust the amount or opacity of the blur out of the box. In order to achieve the desired effect, one would have to, get rid of the blur entirely and go with just a basic fade/ mask as the background, or swap out the UIVisualEffectView with a 3rd party blur library. The down side of the latter option, is most of them are more CPU/ GPU intensive and bloated, hence why I settled on UIVisualEffectView. 

I'll hunt around for better options and seriously consider replacing UIVisualEffectView if I can find a suitable one in the near future.
